# Generated by Django 3.0.4 on 2020-03-23 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='foodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=64)),
                ('typeDscription', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'userTypes',
                'db_table': 'userType',
            },
        ),
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('userLocation', models.CharField(max_length=255)),
                ('userJoinDate', models.DateField()),
                ('userAllergies', models.CharField(max_length=1024)),
                ('userFavorites', models.CharField(max_length=1024)),
                ('userDescription', models.TextField()),
                ('foodType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userDBapp.foodType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'members',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='hostReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostReviewTitle', models.CharField(max_length=255)),
                ('hostReviewDate', models.DateField()),
                ('hostReviewRating', models.SmallIntegerField()),
                ('hostReviewRext', models.TextField()),
                ('hostUser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('hostUserReviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userDBapp.userDetail')),
            ],
            options={
                'verbose_name_plural': 'hostUserReviews',
                'db_table': 'hostUserReview',
            },
        ),
        migrations.CreateModel(
            name='guestReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestReviewTitle', models.CharField(max_length=255)),
                ('guestReviewDate', models.DateField()),
                ('guestreviewRating', models.SmallIntegerField()),
                ('guestreviewRext', models.TextField()),
                ('guestUser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('guestUserReviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userDBapp.userDetail')),
            ],
            options={
                'verbose_name_plural': 'guestUserReviews',
                'db_table': 'guestUserReview',
            },
        ),
    ]
