# Generated by Django 3.0.4 on 2020-03-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDBapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name_plural': 'foodTypes'},
        ),
        migrations.AlterModelTable(
            name='foodtype',
            table='foodType',
        ),
    ]
