# Generated by Django 3.0.4 on 2020-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDBapp', '0003_auto_20200323_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestreview',
            old_name='guestreviewRext',
            new_name='guestreviewText',
        ),
        migrations.RenameField(
            model_name='hostreview',
            old_name='hostReviewRext',
            new_name='hostReviewText',
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='typeDescription',
            field=models.CharField(max_length=1024),
        ),
    ]
